# Generated by Django 3.0.5 on 2020-04-26 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0019_auto_20200421_1710'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='address_projivaniya',
            new_name='address_of_residence',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='data_vidachi',
            new_name='date_of_issue',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='invalid',
            new_name='disability',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='family',
            new_name='family_status',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='otchestvo',
            new_name='middle_name',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='voenoobyazaniy',
            new_name='military_service',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='kem_vidan',
            new_name='passport_authority',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='seria_pasporta',
            new_name='passport_series',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='address_propiski',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='city_projivaniya',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='city_propiski',
        ),
        migrations.AddField(
            model_name='profile',
            name='city_of_residence',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='city_of_residence', to='Bank.City', verbose_name='Город проживания'),
        ),
        migrations.AlterField(
            model_name='deposits',
            name='deposit_type',
            field=models.CharField(choices=[('под 11.3% на 95 дней', 'под 11.3% на 95 дней'), ('под 11.8% на 125 дней', 'под 11.8% на 125 дней'), ('под 12.8% на 185 дней', 'под 12.8% на 185 дней'), ('под 13% на 275 дней', 'под 13% на 275 дней'), ('под 13.2% на 385 дней', 'под 13.2% на 385 дней'), ('под 12.8% на 550 дней', 'под 12.8% на 550 дней'), ('под 12.5% на 735 дней', 'под 11% на 735 дней')], default=0, max_length=900, verbose_name='Тип депозита'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='position',
            field=models.CharField(max_length=20, null=True, verbose_name='Должность'),
        ),
    ]
