# Generated by Django 3.0.5 on 2020-04-26 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0020_auto_20200426_1737'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': 'Счёт'},
        ),
        migrations.AlterModelOptions(
            name='citizenship',
            options={'verbose_name_plural': 'Гражданство'},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'Город'},
        ),
        migrations.AlterModelOptions(
            name='deposits',
            options={'verbose_name_plural': 'Вклады'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Профиль'},
        ),
    ]
