# Generated by Django 3.0.5 on 2020-05-05 16:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0020_auto_20200421_1723'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name_plural': 'Счета пользователей'},
        ),
        migrations.AlterModelOptions(
            name='citizenship',
            options={'verbose_name_plural': 'Гражданство'},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'Города'},
        ),
        migrations.AlterModelOptions(
            name='deposits',
            options={'verbose_name_plural': 'Вклады пользователей '},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name_plural': 'Профили'},
        ),
        migrations.AddField(
            model_name='deposits',
            name='deposit_days',
            field=models.IntegerField(default=0, editable=False, verbose_name='Срок вклада в днях'),
        ),
        migrations.AddField(
            model_name='deposits',
            name='percentage',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=4, verbose_name='Проценты'),
        ),
        migrations.AlterField(
            model_name='deposits',
            name='deposit_creating_date',
            field=models.DateField(default=datetime.date.today, editable=False, verbose_name='Дата открытия вклада'),
        ),
        migrations.AlterField(
            model_name='deposits',
            name='deposit_end_date',
            field=models.DateField(default=datetime.date.today, editable=False, verbose_name='Дата закрытия вклада'),
        ),
        migrations.AlterField(
            model_name='deposits',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=4, verbose_name='Налог'),
        ),
        migrations.AlterField(
            model_name='deposits',
            name='temporary_deposit_income',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, null=True, verbose_name='Доход от вклада'),
        ),
        migrations.AlterField(
            model_name='deposits',
            name='temporary_total_income',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, null=True, verbose_name='Сумма в конце срока'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='job',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Место работы'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='position',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Должность'),
        ),
    ]
