# Generated by Django 3.0.5 on 2020-04-26 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0021_auto_20200426_1955'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': 'Счёта'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Профили клиентов'},
        ),
    ]
