# Generated by Django 3.0.5 on 2020-04-27 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0022_auto_20200426_2000'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name_plural': 'Счета клиентов'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name_plural': 'Профили клиентов'},
        ),
    ]
