# Generated by Django 3.0.5 on 2020-04-27 19:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0023_auto_20200427_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposits',
            name='deposit_creating_date',
            field=models.DateField(default=datetime.date.today, editable=False, verbose_name='Дата открытия вклада'),
        ),
        migrations.AlterField(
            model_name='deposits',
            name='deposit_end_date',
            field=models.DateField(default=datetime.date.today, editable=False, verbose_name='Дата закрытия вклада'),
        ),
        migrations.AlterField(
            model_name='deposits',
            name='deposit_type',
            field=models.CharField(choices=[('под 11.3% на 95 дней', 'под 11.3% на 95 дней'), ('под 11.8% на 125 дней', 'под 11.8% на 125 дней'), ('под 12.8% на 185 дней', 'под 12.8% на 185 дней'), ('под 13% на 275 дней', 'под 13% на 275 дней'), ('под 13.2% на 385 дней', 'под 13.2% на 385 дней'), ('под 12.8% на 550 дней', 'под 12.8% на 550 дней'), ('под 12.5% на 735 дней', 'под 11% на 735 дней')], default=0, max_length=900, verbose_name='Тип вклада'),
        ),
        migrations.AlterField(
            model_name='deposits',
            name='deposit_value',
            field=models.IntegerField(default=0, verbose_name='Сумма вклада'),
        ),
        migrations.AlterField(
            model_name='deposits',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=4, verbose_name='Налог'),
        ),
        migrations.AlterField(
            model_name='deposits',
            name='temporary_deposit_income',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, null=True, verbose_name='Доход от вклада'),
        ),
        migrations.AlterField(
            model_name='deposits',
            name='temporary_total_income',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, null=True, verbose_name='Сумма в конце срока'),
        ),
    ]
