# Generated by Django 3.0.5 on 2020-05-05 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0025_auto_20200505_1336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposits',
            name='tax_rate',
        ),
    ]
