# Generated by Django 3.0.5 on 2020-05-05 10:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0026_remove_deposits_tax_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposits',
            name='deposit_end_date',
            field=models.DateField(default=datetime.date.today, editable=False, verbose_name='Дата закрытия вклада'),
        ),
    ]
