# Generated by Django 3.0.5 on 2020-05-05 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0028_deposits_tax_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposits',
            name='percentage',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=4, verbose_name='Проценты'),
        ),
    ]
