# Generated by Django 3.0.5 on 2020-05-05 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0029_deposits_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposits',
            name='deposit_days',
            field=models.IntegerField(default=0, editable=False, verbose_name='Срок вклада в днях'),
        ),
        migrations.AlterField(
            model_name='deposits',
            name='deposit_type',
            field=models.CharField(choices=[('под 11.3% на 95 дней', 'под 11.3% на 95 дней'), ('под 11.8% на 125 дней', 'под 11.8% на 125 дней'), ('под 12.8% на 185 дней', 'под 12.8% на 185 дней'), ('под 13% на 275 дней', 'под 13% на 275 дней'), ('под 13.2% на 385 дней', 'под 13.2% на 385 дней'), ('под 12.6% на 550 дней', 'под 12.6% на 550 дней'), ('под 13% на 735 дней', 'под 13% на 735 дней')], default=0, max_length=900, verbose_name='Тип вклада'),
        ),
    ]
